name: Python Script CI/CD

on:
  push:
    branches: [ main, master ]  # 包括 main 和 master
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允許手動觸發

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run API test
      run: python -m unittest simple_api_test.py