name: Docker CI/CD with API Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run API test
      run: python -m unittest simple_api_test.py
    - name: Run all tests
      run: python -m unittest discover -v

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t ntust-course-tracker:latest .
    - name: Save Docker image
      run: docker save ntust-course-tracker:latest > image.tar
    - name: Deploy to server
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "$SERVER_SSH_KEY" > deploy_key
        chmod 600 deploy_key
        scp -o StrictHostKeyChecking=no -i deploy_key -P $SERVER_PORT image.tar $SERVER_USER@$SERVER_HOST:~/image.tar
        ssh -o StrictHostKeyChecking=no -i deploy_key -p $SERVER_PORT $SERVER_USER@$SERVER_HOST '
          docker load < ~/image.tar
          docker stop ntust-course-tracker || true
          docker rm ntust-course-tracker || true
          docker run -d --name ntust-course-tracker \
            --restart unless-stopped \
            -v /home/$USER/course_logs:/app/logs \
            ntust-course-tracker:latest
        '